---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
codenotary:
  base_image: notary@home-assistant.io
  signer: notary@home-assistant.io
args:
  BUILD_FROM: ghcr.io/home-assistant/aarch64-base-debian:bookworm
